name:                aoc2018
version:             0.2.0
github:              "blmage/aoc2018"
author:              "blmage"

extra-source-files:
- README.md

description:         Advent of Code 2018.

dependencies:
- base >= 4.7 && < 5
- conduit
- containers
- mtl
- safe
- text

default-extensions:
- LambdaCase
- MultiWayIf
- OverloadedStrings
- PatternGuards
- TypeApplications
- ViewPatterns

library:
  source-dirs: src

executables:
  aoc2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
